[package]
name = "gui"
version = "0.1.0"
authors = ["ENGO150 <v.smejkal06@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.16.0"
